services:
    supercru_extendedcms.elfinder_id.form.type:
        class: SuperCru\ExtendedCmsBundle\Form\Type\ElFinderIdType
        arguments:
            - "@doctrine_phpcr.odm.document_manager"
        tags:
            - { name: "form.type", alias: "elfinder_id" }
    supercru_extendedcms.adapter.elfinder.id_phpcr_driver:
        class: SuperCru\ExtendedCmsBundle\Adapter\ElFinder\IdPhpcrDriver
        arguments:
            - "@doctrine_phpcr"
            - "%cmf_media.persistence.phpcr.manager_name%"
            - "@cmf_media.persistence.phpcr.manager"
            - "@cmf_media.templating.helper"
            - "%cmf_media.imagine.filter.elfinder_thumbnail%"
