services:
    supercru_extendedcms.twig.extension.footer:
        class: SuperCru\ExtendedCmsBundle\Twig\FooterExtension
        arguments: ["@doctrine_phpcr.odm.document_manager", "%supercru.extenedcms.footer.site_path%"]
        tags:
            - { name: "twig.extension" }

    supercru_extendedcms.listener.menu_node:
          class: SuperCru\ExtendedCmsBundle\Listener\MenuNodeListener
          arguments:
              - "@knp_menu.menu_provider"
              - "@security.authorization_checker"
              - "@security.token_storage"
          tags:
              -   name: kernel.event_listener
                  event: cmf_menu.create_menu_item_from_node
                  method: onCreateMenuItemFromNode
